services:
  product-mongodb:
    image: mongo:7.0.5
    container_name: product-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 3435
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data/mongodb:/data/db
    restart: unless-stopped
